[package]
name = "locologic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
locodrive = { git = "https://github.com/juhu1705/locodrive" }
