blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/juhu1705/locologic/discussions
    about: Please ask and answer questions about this project here.
  - name: LocoLogic documentation
    url: https://juhu1705.github.io/locologic/doc/locologic
    about: The rust doc of this project
  - name: LocoDrive
    url: https://github.com/juhu1705/locodrive/
    about: The connection to the model train railroad and message parsing
  - name: Model Train contribution project board
    url: https://github.com/users/juhu1705/projects/5
    about: A listing of all model railroad based Issues and their work state
