blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/juhu1705/locodrive/discussions
    about: Please ask and answer questions about this project here.
  - name: Rocrails protocol documentation
    url: https://wiki.rocrail.net/doku.php?id=loconet:ln-pe-en
    about: A listing on all messages
  - name: locodrive documentation
    url: https://juhu1705.github.io/locodrive/doc/locodrive
    about: The rust doc of this project
  - name: Model Train contribution project board
    url: https://github.com/users/juhu1705/projects/5
    about: A listing of all model railroad based Issues and their work state
